---

- file:
    path: /mnt/app/nginx/logs
    state: directory
    mode: 0777

- file:
    path: /mnt/app/nginx/conf.d
    state: directory
    mode: 0777

- template:
    src: jenkins.bppj.j2
    dest: /mnt/app/nginx/conf.d/jenkins.bppj.conf


- name: Nginx | Docker Nginx
  docker_container:
    name: nginx
    image: nginx:1.13.8-alpine
    detach: true
    pull: true
    state: started
    restart: yes
    restart_policy: always
    links:
        - jenkins
    ports:
    - "80:80"
    - "443:443"
    volumes:
    - /mnt/app/nginx/conf.d:/etc/nginx/conf.d/
    - /mnt/app/nginx/logs:/var/log/nginx/log/
